version: "3.9"

services:
  go-container:
    container_name: python-container
    # image: python-test:latest
    build: 
      dockerfile: ./python.Dockerfile
      context: .
    environment:
      - INPUT_ENV_VAR="it passed through"
    volumes:
      - ".:/etc/"
    entrypoint: /bin/bash /etc/startup.sh